### ISSUE TITLE
lateinit property edtWidth has not been initialized

### ISSUE THREAD

**Issue by ihsan2** [dicodingacademy/a51-android-pemula-labs#4]
Saat saya run app muncul error kayak gini kotlin.UninitializedPropertyAccessException: lateinit property edtWidth has not been initialized

**Comment by arifaizin** [comment]
Kemungkinan karena belum edtWidth belum diinisialisasi mas.. 
Pastikan sudah ada kode `edtWidth = findViewById(R.id.edt_width)
`
