### ISSUE TITLE
null handler on onClick

### ISSUE THREAD

**Issue by youngpadawan** [dicodingacademy/a51-android-pemula-labs#6]
on MainActivity Code:

 override fun onClick(v: View?) {
        if(v.id == R.id.btn_calculate) {

will be invalid on recent Kotlin version and replaced with

 override fun onClick(v: View?) {
        if(v?.id == R.id.btn_calculate) {

and need to erase the following code

//            var isInvalidDouble = false
//            if(length == null) {
//                isInvalidDouble = true
//                this.edtLength.error = "Panjang ini harus berupa angka yang valid"
//            }
//
//            if(width == null) {
//                isInvalidDouble = true
//                this.edtWidth.error = "Lebar harus berupa angka yang valid"
//            }
//
//            if(height == null) {
//                isInvalidDouble = true
//                this.edtHeight.error = "Tinggi harus berupa angka yang valid"
//            }

and change the last if

if(!isEmptyFields && isInvalidDouble) {  to =>  if(!isEmptyFields) {

**Comment by auliaekadharma** [comment]
Alt+Enter and you can choose "surround with null check"
it will add new line under onClick method : if (v != null) to check v isNot null

override fun onClick(v: View?) {
        if (v != null) {
            if (v.id == R.id.btn_calculate) {
            
            . . .
        
            }
       }
}

**Comment by arifaizin** [comment]
Updated di push terbaru ya
